[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = ["@openzeppelin/=node_modules/@openzeppelin/"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
monad_testnet = "${MONAD_TESTNET_RPC_URL}"

[etherscan]
monad_testnet = { key = "${MONAD_EXPLORER_API_KEY}", url = "${MONAD_EXPLORER_VERIFY_URL}", chain = 10143 }
